default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mini_bulletin_board_app_development

test:
  <<: *default
  database: mini_bulletin_board_app_test

production:
  <<: *default
  database: mini_bulletin_board_app_production
  username: mini_bulletin_board_app
  password: <%= ENV['MINI_BULLETIN_BOARD_APP_DATABASE_PASSWORD'] %>
